name: myenv
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9  # Or your Python version (3.9, 3.10, 3.11, but not 3.12)
  - pytorch=2.3.0+cpu
  - torchvision=0.14.0+cpu # Or your desired version
  - torchaudio=2.3.0+cpu # Or your desired version
  - streamlit
  - pandas
  - yfinance
  - transformers
  - sentencepiece
  - protobuf
  - feedparser
  - matplotlib
  - joblib
  - scikit-learn
